ray-project/rayfed

.gitignore
fed/_private/constants.py
fed/_private/fed_actor.py
fed/barriers.py
fed/utils.py

1. party name can be injected to log msg automatically, so remove the explicit writing
2. align log format to RAY
3. ignore .vscode folder

Remove `party` field from log message.

---

fed/_private/fed_call_holder.py
fed/api.py
fed/barriers.py
fed/fed_object.py
fed/utils.py
tests/test_cache_fed_objects.py

In this PR, we introduce a simple cache for transferring fed objects across parties. 
Before this PR, in the following script, the fed object would be transferred twice from Alice to Bob, while it only be transferred once after this PR.
```python
o = f.party("alice").remote()
o1 = g.party("bob").remote(o, 1) # transferring `o`
o2 = g.party("bob").remote(o, 2) # not transferring `o` any longer from this PR on
```
This is also useful for `fed.get()` a sending/sent fed object.

[Perf Optimization] Cache fed objects for further using if needed.

---

README.md
setup.py

In this PR, we changed the package name to `rayfed`, as well as some other necessary fields.
The related issue is https://github.com/ray-project/rayfed/issues/38

Change package name to rayfed

---

fed/_private/fed_call_holder.py
fed/api.py
fed/barriers.py
fed/utils.py
tests/test_enable_tls_across_parties.py
tests/test_transport_proxy_tls.py

In this PR, we simplify the TLS configuration, and it can fix #56 .
After this PR, TLS configuration should be as the following:
```python
cert_config = {
"ca_cert": os.path.join(cert_dir, "server.crt"),
"cert": os.path.join(cert_dir, "server.crt"),
"key": os.path.join(cert_dir, "server.key"),
}
fed.init(cluster=cluster, party="ALICE", tls_config=cert_config)
```
Close #56

feat: simplify tls config.

---

.github/workflows/test_on_ray1.13.0.yml
.github/workflows/test_on_ray2.0.0.yml
fed/_private/compatible_utils.py
fed/_private/constants.py
fed/api.py
fed/utils.py
tests/test_transport_proxy.py
tests/test_transport_proxy_tls.py

We make that RayFed is able to be compatible with the lower versions of Ray.
In this PR, we tested it on Ray1.13.0, that means RayFed is able to be run on Ray1.13.0 officially.

Be compatible with lower versions of ray.

---

fed/api.py
setup.py

- Correct tls_config docstring
- Bump to 0.1.1a0 since 0.1.0b1 is shipped already.

docs: correct tls config docstring.

---

fed/_private/global_context.py
fed/api.py
fed/barriers.py
tests/test_reset_context.py

The `global_context` incrementally generates the fed task id. It should be reset after calling `fed.shutdown` so that the fed task id can grow from 0 again.

clear global_context after shutdown

---

fed/api.py
fed/barriers.py
tests/test_ping_others.py

Ping other parties by the `ProxyActor` instead of the driver, so that it can carry grpc meta and the code can be more easy to maintain.
Close #117

ping from ProxyActor & carry grpc meta

---

fed/cleanup.py
tests/test_repeat_init.py

The send queue won't be cleared when shutting down rayfed, the message left in the queue may be read in the next session, i.e. the next time calling `fed.init` , which is one of the reason what happened in this [issue](https://github.com/secretflow/secretflow/issues/529)
Note that this PR couldn't completely fix that problem because there're also flying request after `fed.shutdown`, will open another PR.

Reset sending queue after `fed.shutdown`

---

fed/api.py
fed/utils.py
tests/without_ray_tests/test_utils.py

This PR is used to validate the address passed into `fed.init()`, leading it following one of the rules:
- `local` for starting a new cluster, or `localhost` for connecting a local cluster.
- 'ip:port' format, where the IP needs to follow the IP address specifications and the port is a number.
- 'hostname:port' format, where the hostname is a string and the port is a number.
- An HTTPS or HTTP link starting with 'https://' or 'http://'.

Validate address and cluster info.

---

fed/_private/compatible_utils.py
fed/api.py
tests/test_internal_kv.py
tests/test_transport_proxy.py
tests/test_transport_proxy_tls.py

Fed will try to init the internal_kv when importing the "compatible_utils" module.
This will cause problem in client-server mode, because the import action comes first before the call of`ray.init`, and at that time, the flag `ray._private.client_mode_hook.is_client_mode_enabled` that internal_kv relies on is not "True" as expected.
This PR fixes it by only initializing internal_kv when explicitly calling `_init_internal_kv` and only init once.

not init kv until `fed.init` called

---

fed/api.py
fed/barriers.py
fed/config.py
tests/test_setup_proxy_actor.py

This is the first step of #134 
This PR provides `cross_silo_send_resource_label` and `cross_silo_recv_resource_label` config in `fed.init` and convert them to the "resources" field of ActorClass.options.

Setup ProxyActor Config [1/N]

---

benchmarks/many_tiny_tasks_benchmark.py
fed/proxy/barriers.py

Before this PR, we'll create a new channel object when sending data. We reuse that in this PR to make code clean.
Also, we did a benchmark from @fengsp(Thanks for the contribution) for this PR, and the result is not too good.
The baseline(before this PR) is:
```
num calls: 10000
total time (ms) =  79241.70279502869
per task overhead (ms) = 7.924171590805054
```
and the current result after this PR is:
```
num calls: 10000
total time (ms) =  78388.72385025024
per task overhead (ms) = 7.83887369632721
```

Reuse channel to send data.

---

fed/_private/fed_call_holder.py
fed/api.py
tests/test_api.py
tests/test_fed_get.py

Before this PR, if you miss the `party` on creating a fed actor, the program will hang.
In this PR, we address that by raising a necessary ValueEerror.
Please see the unit test for more details.

Enhance the value error when missing a reqiured param.

---

fed/_private/compatible_utils.py
fed/proxy/barriers.py
fed/utils.py
tests/test_transport_proxy.py

Turns out importlib.metadata is a standard library in Python 3.8 and later, making it incompatible for py37

Fix importlib.metadata error in python3.7

---

fed/_private/constants.py

`Anonymous` is confusing somehow as the default job name. Give it an explicit name.
```
2023-12-11 12:29:32 INFO barriers.py:295 [bob] -- [Anonymous] SenderProxyActor has successfully created.
```
```
2023-12-11 12:29:32.598 INFO barriers.py:295 [bob] -- [Anonymous_job] SenderProxyActor has successfully created.
```

feat: use `Anonymous_job` as default job name.

---

fed/api.py

Use None as default value for `job_name` in `fed.init` just same as other params.

refactor: use None as default value for job_name param in init.

---

docs/doc-requirements.txt
docs/source/api.rst
docs/source/conf.py
docs/source/usage.rst
fed/api.py
fed/config.py

docs: add api doc.

---

.github/workflows/unit_tests_for_protobuf_matrix.yml
.github/workflows/unit_tests_on_ray_matrix.yml
README.md
benchmarks/many_tiny_tasks_benchmark.py
dev-requirements.txt
fed/tests/client_mode_tests/test_basic_client_mode.py
fed/tests/multi-jobs/test_ignore_other_job_msg.py
fed/tests/multi-jobs/test_multi_proxy_actor.py
fed/tests/serializations_tests/test_unpickle_with_whitelist.py
fed/tests/simple_example.py
fed/tests/test_exit_on_failure_sending.py
fed/tests/test_internal_kv.py
fed/tests/test_utils.py
requirements.txt
test.sh

TODO: client mode does not work on ray>2.4

feat: unittest on more ray versions.

---

fed/_private/global_context.py
fed/_private/message_queue.py
fed/api.py
fed/cleanup.py
fed/config.py
fed/tests/test_cross_silo_error.py
fed/tests/test_listening_address.py
fed/tests/test_transport_proxy.py
fed/tests/test_transport_proxy_tls.py

feat: no wait for data sending on error.
